version: '3'
services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    restart: unless-stopped
    privileged: true
    ports:
      - "80:80"
      - "443:443"

  vpnserver:
    image: weejewel/wg-easy
    container_name: VPNserver
    restart: unless-stopped
    ports:
      - "51001:51820/udp"
      - "51001:51821/tcp"   
    volumes:
      - ~/.wg-easy:/etc/wireguard
    environment:
      - WG_HOST=localhost
      # - WG_HOST=172.16.100.10
      - PASSWORD=admin
      - WG_PORT=51000
      - WG_MTU=1420
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEFAULT_ADDRESS=10.0.0.x
      - WG_DEFAULT_DNS=1.1.1.1, 1.1.0.0
      - WG_ALLOWED_IPS=0.0.0.0/0
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1

# docker exec -it VPNserver bash