services:
  rancher:
    container_name: rancher
    restart: unless-stopped
    # ports:
    #   - 80:80
    #   - 443:443
    privileged: true
    image: rancher/rancher:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: host     
    volumes:
    - ./rancher:/var/lib/rancher

# docker ps
# docker logs rancher 2>&1 | grep "Bootstrap Password:"      
# docker logs rancher 2>&1 | Select-String "Bootstrap Password:"

  
# aP@ssw0rdx12


